### PR TITLE
Turns enable tabs off by default. Fixes #1.

### LINKED ISSUE #1: 'Enable automatic tab when max length in a input field is reached.' causes problems
'Enable automatic tab when max length in a input field is reached.' in my case leads to constant automatic tabbing in the case of pages like youtube or more local swiss pages like salt.ch. Of course the problem is fixed by turning the feature off. Probably make the feature turned off by default. Or do you think that there is an actual issue to be fixed? Probably you are reacting wrongly to a missing max length tag or one that is changed by a script.

### PR DESCRIPTION
**Pull request by benelot**
Enable automatic tabbing seems to cause problems on several pages. Therefore we turn it off by default.

### CODE REVIEW

**Comment by benelot** [comment]
Can you review this change? I think it should set the default option of the extension to false. Now, how to update the extension in google chrome store? I have no idea.

**Comment by ThomasArdal** [comment]
@benelot Wouldn't it be better to actual fix the problem (as you mention in the issue as well)? I'm not sure I totally understand the problem. Could you send an URL containing the problem as well as a description on what goes wrong on that particular page?

**Comment by benelot** [comment]
I am not sure if you want to have this as a default behavior, because I as a user like to be actually limited by the max length so that I can see that I am not allowed to enter more content into the field. So auto-tabbing does not sound to me like a very good thing to do. Furthermore it somehow does not relate to the original gInfinity purpose which is the automatic google search page loading, isn't it? So I also would not expect an extension like this to do something like auto-tabbing on input fields.

Am I right that you implemented the extension? The point is that I never implemented anything like a chrome extension. I hardly found the way to set the default option. So you might be more knowledgeable about the solution to the problem.

But I had a look at it and I found out that the script behaves wrongly when an input field does not have a maxLength attribute set. If you go to youtube.com and you type into the search input field with the auto-tabbing option on, it auto-tabs right after the first letter.

I think the cause of it is in the ginfinity.js line 171:

if (event.target.maxLength) {

which should actually skip the input field if the max length attribute is not there. From what I read, the default value of the maxlength if not set by the developer is 524288 (source: W3C).

So if I understand it correctly, this if always passes because the event.target.maxLength in chrome returns -1 if it is not set. I tested this with a simple self-made form. From what I have seen, it can simply be fixed by writing:

if(event.target.maxLength > 0) {

Should I commit this as well? What do you think?

**Comment by ThomasArdal** [comment]
@benelot It's correct that I'm the original developer of this extension. In fact I created a bunch of different extensions and decided to merge them all into this one - gInfinity.

Weather or not people want the individual features enables, is really up to them. I believe that all features should be enabled by default. The reason for some of the features being disabled by default, were that I would test them and get feedback from users before enabling them. But then I sort of left the the project :smile:

Thank you for the contribution. I will try to publish a new version to the store.

**Comment by benelot** [comment]
Ok, all right, I am happy that I could help :)

**Pull request closed without merging**
